✔ Bug: Browser: Open vanilla file -> TypeError: GameDir.get_vanilla_file() missing 1 required positional argument: 'relative_file_path' @done(23-09-03 21:27)